### ISSUE TITLE
Async shared file locks test fails with node v4

### ISSUE THREAD

**Issue by trentm** [joyent/node-lockfd#8]
This test case is failing in 2.x using node v4:

```
# Shared file locks (async)
ok 26 acquired lock successfully
ok 27 unlocked successfully
ok 28 acquired lock successfully
ok 29 unlocked successfully
not ok 30 Correct final order
  ---
    operator: deepEqual
    expected: [ 'workload 2', 'workload 1' ]
    actual:   [ 'workload 1', 'workload 2' ]
  ...
```

**Comment by melloc** [comment]
The problem seems to be [this `process.nextTick`](https://github.com/joyent/node-lockfd/blob/adc9aba9d5891b0b7e6f67685ea21d94cc5a5f7a/test/unit/flock.test.js#L48). When called from the same stack as [this `v8plus_call`](https://github.com/joyent/node-lockfd/blob/adc9aba9d5891b0b7e6f67685ea21d94cc5a5f7a/src/lockfd.c#L138), it's somehow attached to the same tick as the following `setTimeout`, which means `getSecondLock()` doesn't run until after `fd1` has been unlocked.

Changing from `process.nextTick` to `setTimeout` fixes the test, but that's just the consumer working around the issue. To make sure someone else doesn't accidentally stumble onto this weirdness, I've updated `lib/index.js` to always defer calling the user's callback. See the CR [here](https://cr.joyent.us/5591).
